Update secrets.yml

diff --git a/.github/workflows/secrets.yml b/.github/workflows/secrets.yml
--- a/.github/workflows/secrets.yml
+++ b/.github/workflows/secrets.yml
@@ -1,14 +1,21 @@
+
 name: Testing Secret Variables
 
 on:
-  workflow_dispatch
-env:
-      ACTIONS_STEP_DEBUG: true
+  workflow_dispatch:
+
 jobs:
   test_context_variables:
     runs-on: ubuntu-latest
+
     steps:
-      - name: "Checking Secret Variable"
+      - name: Checking Secret Variable
+        env:
+          MY_KEY: ${{ secrets.MY_KEY }}
         run: |
-          echo "Secret Value : ${{ secrets.MY_KEY }}"
-          ${{ secrets.MY_KEY }}
+          if [ -n "$MY_KEY" ]; then
+            echo "Secret is available"
+          else
+            echo "Secret is missing"
+            exit 1
+          fi
